# Site settings
title:       42ish
email:       logan.graham@balliol.ox.ac.uk
author:      Ali Rizvi and Logan Graham
description: "Our thoughts online."
baseurl:     "/blog"
url:         "http://42ish.com"
date_format: "%b %-d, %Y"

# Google analytics
google_analytics: UA-51657413-3

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: logangraham
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username: logangraham
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
